import random
import turtle

turtle.reset()
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )
turtle.forward( random.randint(0,200) )
turtle.left( random.randint(0,180) )
turtle.pensize( random.randint(1,10) )

turtle.exitonclick()


